### ISSUE TITLE
Geog 120-style Group By tool

### ISSUE THREAD

**Issue by josephholler** [GIS4DEV/GIS4DEV.github.io#15]
If you'd like access to the `group by` tool we used in geog 120, you can try installing our new [MiMiGIS plugin](https://github.com/GIS4DEV/MiMiGIS) by downloading the code from GitHub:

![image](https://user-images.githubusercontent.com/10039423/109984549-e19b6a00-7cd1-11eb-958c-87625716829b.png)

And then install the plugin from Zip in QGIS. I think MacOS may automatically unzip the files as you download, in which case they may need to be re-compressed into a zip in order to install.

Alternatively, I have versions of the geog 120 models in [this repository](https://github.com/GIS4DEV/QGISmiddleburyAlgs)

**Comment by josephholler** [comment]
The file must be unzipped before you can use it...

**Comment by evankilli** [comment]
For some reason still, whenever I try to install the plugin, it allows me to _install_ but gives me the error that it could not load the plugin. Do you have more detailed installation instructions?

**Comment by majacannavo** [comment]
Did you unzip the plugin folder first? I think it should work if you take the zipped folder and use that in the "install plugin from zip" menu in QGIS.

**Comment by evankilli** [comment]
Nope, left it unzipped, but regardless of zipping, it stil gives the same "could not load plug-in" error

**Comment by evankilli** [comment]
I can copy the error message into here if that helps

**Comment by majacannavo** [comment]
Try this: On the repository page, scroll down to the ReadMe document and right below the title, click the "download" link. Then try installing that zip. I'm not totally sure what the difference is between the two download options, but the "download" link has been working for me.

**Comment by evankilli** [comment]
I've already tried downloading from both sources, and it doesn't seem to be working for either

**Comment by mtango99** [comment]
I think you can also just use the same aggregation tool we used in the first model

________________________________

**Comment by evankilli** [comment]
@mtango99 That's probably what I'll end up doing when I figure it out

**Comment by majacannavo** [comment]
I'm so sorry it's not working--I'm not sure what the problem is, but we should definitely look into it.

**Comment by josephholler** [comment]
I have a feeling there's confusion between loading a plug-in to qgis vs adding a single model. You can add the .model3 files to the processing toolbox through the red/grey gear icon menu we used to create our own model. One of the options is to add model to toolbox.

**Comment by evankilli** [comment]
I'll try adding the models from the repository instead of trying to install the plugin then
