### ISSUE TITLE
Adding two fields to copy in Join Attributes by Field Value

### ISSUE THREAD

**Issue by sanjana-roy** [GIS4DEV/GIS4DEV.github.io#17]
I was wondering how we were to add two fields to copy to the algorithm Join Attributes by Field Value. Joe let me know how to do this and asked me to add it on the Issue page. Separating the field values by a semicolon and writing it out as a Pre-calculated value (similar to the Field Calculator equations) worked for me: 

'TargetID;' + @TargetWeight

**Comment by josephholler** [comment]
Thanks for posting this!

To add some background, I don't think that the documentation for join attributes by field value​` documents this well.​ If I recall correctly, I sorted out how to format a list of fields by running the tool outside of Graphic Modeler and observing how the parameters were formatted in the processing log when using more than one join field.

To add to troubleshooting advice, when you run a tool outside of Model Builder, pay attention to how the parameters appear in the log.
________________________________
