### ISSUE TITLE
Dartmouth Atlas HSAs: fix invalid geometries

### ISSUE THREAD

**Issue by mtango99** [GIS4DEV/GIS4DEV.github.io#19]
There are some invalid geometries in my layer-- did this happen to anyone else? I am trying to clip the HSAs to VT. If I change settings to ignore invalid geometries, it runs but doesn't include the invalid geometries in the output, leaving a few holes. Any way to fix invalid geometries?

**Comment by josephholler** [comment]
You may leave the geometries unchanged and go for a *select by location* approach instead. It'll look fine in the final web map.

**Comment by mtango99** [comment]
I got a "no spatial index exists for input layer" error when trying to run the select by location tool-- so I'm just gonna select by hand.

**Comment by josephholler** [comment]
Error or warning?  The warning is ok. It just means that it'll take a little bit longer.
