### ISSUE TITLE
3 models or 2 models?

### ISSUE THREAD

**Issue by stevenmontilla** [GIS4DEV/GIS4DEV.github.io#20]
Hi! I was wondering if we need to have separate models for the preprocessing of the homeland security hospital data and another one for the Model to preprocess target features or should the two models be joined into one?

**Comment by josephholler** [comment]
I'll leave that up to you. One model definitely has to be specific to the characteristics of the hospital dataset. If you want to try to tease out more general-purpose preprocessing tasks from that into a third model, that'd be cool but not necessary.

**Comment by josephholler** [comment]
and officially, you may do the preprocessing in normal QGIS if necessary, while documenting your steps.

**Comment by evankilli** [comment]
@josephholler given that this is pretty much serving as my de facto Intro to QGIS (having taken 120 when it was still ArcGIS, Spring '18), where else would we be doing the preprocessing?

**Comment by mtango99** [comment]
It’s just the difference between using a model and doing it step by step I think

________________________________
