### ISSUE TITLE
qgis2web issue

### ISSUE THREAD

**Issue by daptx** [GIS4DEV/GIS4DEV.github.io#25]
When creating the map for qgis2web, I went into the properties of one of my layers (the catchment areas) and modified the attribute tables' titles, so for example changing the name TargetID to ZipCode. However, when I updated my map, I ended up with a white screen. If anyone knows the reason behind this travesty, please let me know. Grazie!

**Comment by josephholler** [comment]
I was just writing to ask clarification about whether you were editing layers in QGIS and getting unexpected blank screen in the plugin, or whether the blank screen was in the web browser once trying to publish the map.  I suppose closing the issue means that you solved it?  How?

**Comment by daptx** [comment]
Hi Joe! I was editing the layers directly in QGIS and getting the blank screen in the plugin. I went back to the videos and followed the 'Publish to Leaflet' tutorial and it accomplished what I was aiming for. I was just testing to see if I could facilitate the process on Q!
