### ISSUE TITLE
Which pages/chapters do we need to read?

### ISSUE THREAD

**Issue by majacannavo** [GIS4DEV/GIS4DEV.github.io#27]
I'm a bit confused about the reading assignment for Wednesday (originally for tomorrow). On the page for that lesson it says we're reading chapters 2 and 3 (pp. 21-43), but when I downloaded chapters 2 and 3 it came out to pages 27-54. I just wanted to confirm whether we should go by chapters or page numbers!

**Comment by vinfalardeau** [comment]
I think the chapters are on pages 27-54 when you access it through the DOI link, but they line up with pages 21-43 in the pdf of the whole book (in the gis4dev literature repository), so it should be fine to go by chapters

**Comment by majacannavo** [comment]
Awesome thanks Vincent!
