### ISSUE TITLE
"Author Identity Unknown" error

### ISSUE THREAD

**Issue by brookelaird** [GIS4DEV/GIS4DEV.github.io#28]
Hi all,

anyone know what this error means or how to solve it? I am trying to post from my local git hub onto the web version and it has been working all night, and now I am getting this error :( Not sure if it is a log-in issue because I am still all logged in 

[
<img width="519" alt="Screen Shot 2021-03-08 at 11 48 29 PM" src="https://user-images.githubusercontent.com/69313113/110420296-fe84c400-8068-11eb-9309-ea10340515a8.png">
](url)

**Comment by alandaux** [comment]
I've had this same problem, seems like a weird glitch. If you just open preferences and make sure you're logged into git, the error goes away (even if you are already logged in, just seems like you have to remind github desktop that it DOES know who you are). When I was looking at solutions online last week, there were also suggestions to just restart the program if the first thing doesn't work.

**Comment by brookelaird** [comment]
Thanks @alandaux and @josephholler ! I played around in the preferences and the error went away.
