### ISSUE TITLE
Exporting rasters from GRASS to QGIS?

### ISSUE THREAD

**Issue by vinfalardeau** [GIS4DEV/GIS4DEV.github.io#32]
Has anyone figured out how to export rasters from GRASS to QGIS to do more stylization?  And do we need to stylize them into proper maps or are the images themselves ok?  So far, when I've tried to export raster layers to GeoTIFFs from GRASS the outputs have instead been wacky TextEdit documents (working on a Mac) that QGIS hasn't been able to read.  Within the export window (which is running r.out.gdal) I've tried different data types (byte, uint, float32, float64...) but it keeps having trouble with making GeoTIFFs directly.

I've actually found a much more convoluted way to get rasters over from GRASS to QGIS, but it's tricky – exporting to an XYZ file with data type Float64, which on a Mac seems to create a TextEdit document, from which you can select all & copy/paste into an actual .txt plain text, which you can drag into QGIS and warp into a TIFF with the tool GDAL - Warp (Reproject). Now I'm mostly just wondering whether there is an easier way!?

Probably overthinking it

**Comment by emmaclinton** [comment]
Right click on layer --> export as GTIFF --> manually putting .tif at the end of the file name worked for me?

**Comment by vinfalardeau** [comment]
Oh man, it was really that simple, oof.  Thanks Emma!

**Comment by emmaclinton** [comment]
Np! Sounds like a pretty epic work-around you came up with
