### ISSUE TITLE
Linking RE-Rosgen content to index page of personal repo

### ISSUE THREAD

**Issue by emmaclinton** [GIS4DEV/GIS4DEV.github.io#34]
Having some trouble linking my RE-Rosgen content (the HEGSRR-Replication-Report.md) to my index page in my personal repo so that it shows up as a page on my site. Does anyone know how to do this?

**Comment by emmaclinton** [comment]
once again, please disregard

I just had to move the .md into the other index repo and link to it from there (thanks Maja!)

**Comment by emmaclinton** [comment]
Wait no now my links to things in the other repository aren't working (I forgot about that). Does anyone know of a work-around?

**Comment by josephholler** [comment]
You can copy images over into an assets folder in your .github.io repository and link to them there.
For other things, you probably want the reader to go to your other repository to see them, so you can copy addresses of specific files over there... so use whatever the address is in your web browser when you navigate to that file, e.g. the metadata write-up is here: https://github.com/GIS4DEV/RE-rosgen/blob/main/data/metadata/readme.md or maybe link to the repository itself (i.e. https://github.com/GIS4DEV/RE-rosgen) and give a little guidance where to look within that.
________________________________
