### ISSUE TITLE
Unable to connect to PostGIS

### ISSUE THREAD

**Issue by emmaclinton** [GIS4DEV/GIS4DEV.github.io#36]
Is anyone else unable to connect to PostGIS on QGIS? I keep getting asked for my credentials and in the same window getting the message "timeout expired" and "sslmode = disable." I'm unable to open the DB.

**Comment by josephholler** [comment]
Interesting. I am also having difficulty connecting, and I'm following up with IT.

**Comment by vinfalardeau** [comment]
The server/database appears to be back up now.  I had the same issue yesterday, but I can log in now

**Comment by josephholler** [comment]
Yes, it does appear to be back!

**Comment by josephholler** [comment]
I never got a solid answer as to why this happened, other than the service had stopped, and IT restarted it on Saturday.
