### ISSUE TITLE
C Stack usage is too close to the limit?

### ISSUE THREAD

**Issue by emmaclinton** [GIS4DEV/GIS4DEV.github.io#37]
Hi everyone, 

I am working through the R workshop and trying to reproject London boroughs. I'm getting the error "Error: C stack usage  7970096 is too close to the limit." I'm getting a similar error when I try to visualize the first ten features of "lnd."

I redownloaded the packages we're working with and I tried using ulimit in Terminal to increase the R environment stack size but it doesn't seem to be working. Does anyone know what the issue might be?

**Comment by josephholler** [comment]
it happened on this step?

`london_27700 <- lnd %>%
  st_transform(crs = st_crs(27700))`

This is a small dataset and the process runs in an instant. Can you check if your computer is running out of RAM? Do you have other huge datasets loaded in R? Maybe a reboot is in order... In Windows, task manager will tell you about resource usage. In MacOS?

**Comment by emmaclinton** [comment]
Restarted, cleaned memory, and redownloaded RStudio and now it's working! Thanks.
