### ISSUE TITLE
Moving picture files into folders

### ISSUE THREAD

**Issue by chriskgernon** [GIS4DEV/GIS4DEV.github.io#5]
I am trying to move my picture files from the master repo to the QGIS and SAGA folders I've created in the repo. Does anyone know how to do this using the online version of github or github from the command line?

**Comment by josephholler** [comment]
Online, if you edit a file, you can add subfolders to the file name.
e.g. my `distanceGraph.html` was shown as being in `GIS4DEV.github.io/distanceGraph.html`
I changed the file name to `graph/distanceGraph.html`, and it automatically creates a graph folder and moves the file into it.
If you need to move a file back up to a root folder, type two periods and a slash, which means go up one folder: `../`
